#!/usr/bin/env python3
"""
Spec sync for Sonic.
- Builds docs/spec/codebase_map.md from source tree
- Optionally exports OpenAPI via api/generate_openapi.py if present
- (Optional) dumps Pydantic JSON Schemas if you wire emitters

Usage:
  python scripts/spec_sync.py
  python scripts/spec_sync.py --schemas-only
"""
from __future__ import annotations
import argparse
import os
from pathlib import Path
import subprocess
import sys
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DOCS_SPEC = ROOT / "docs" / "spec"
DOCS_SCHEMAS = ROOT / "docs" / "schemas"
IGNORE_DIRS = {".git", ".idea", ".vscode", "node_modules", ".venv", "venv", "dist", "build", "__pycache__"}

def walk_code(paths: Iterable[Path]) -> list[str]:
    exts = {".py", ".ts", ".tsx", ".js", ".jsx"}
    rows: list[str] = []
    for base in paths:
        for dp, _, files in os.walk(base):
            parts = Path(dp).parts
            if any(p in IGNORE_DIRS for p in parts):
                continue
            for f in files:
                if Path(f).suffix in exts:
                    p = Path(dp) / f
                    rows.append(str(p.relative_to(ROOT)))
    rows.sort()
    return rows

def write_codebase_map(rows: list[str]) -> None:
    DOCS_SPEC.mkdir(parents=True, exist_ok=True)
    out = ["# Codebase Map\n",
           "_Generated by `scripts/spec_sync.py`. Edit the source, not this file._\n"]
    last_top = None
    for r in rows:
        top = r.split(os.sep)[0]
        if top != last_top:
            out.append(f"\n## {top}\n")
            last_top = top
        out.append(f"- `{r}`")
    (DOCS_SPEC / "codebase_map.md").write_text("\n".join(out), encoding="utf-8")
    print("Wrote docs/spec/codebase_map.md")

def maybe_generate_openapi() -> None:
    gen = ROOT / "api" / "generate_openapi.py"
    if gen.exists():
        print("Generating OpenAPI via api/generate_openapi.py ...")
        subprocess.run([sys.executable, str(gen)], check=False)

def ensure_dirs() -> None:
    (ROOT / "docs" / "actions").mkdir(parents=True, exist_ok=True)
    DOCS_SCHEMAS.mkdir(parents=True, exist_ok=True)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--schemas-only", action="store_true")
    args = parser.parse_args()

    ensure_dirs()
    if not args.schemas_only:
        rows = walk_code([ROOT])
        write_codebase_map(rows)
        maybe_generate_openapi()

    # Hook: if you add schema emitters, call them here
    # e.g., subprocess.run([sys.executable, "scripts/emit_schemas.py"], check=False)

if __name__ == "__main__":
    main()
