
"""fun_core package – auto‑generated by ChatGPT on 2025-07-31 04:06:21 UTC"""

from .fun_router import router as fun_router
from .registry import FunRegistry, FunType  # services registry and enum
from .models import FunContent  # pydantic model for API responses

__all__ = ["fun_router", "FunRegistry", "FunType", "FunContent"]
