
"""fun_core package – auto‑generated by ChatGPT on 2025-07-31 04:06:21 UTC"""

from .fun_router import router as fun_router
from .registry import FunRegistry, FunType, FunContent  # re‑export for convenience

__all__ = ["fun_router", "FunRegistry", "FunType", "FunContent"]
